name: Laravel

on:
  push:
    branches: [ "main" ]
  
jobs:
  laravel-tests:

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3
        ports:
          - 3306:3306

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.2'
    - uses: actions/checkout@v4
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install --optimize-autoloader
    - name: Generate key
      run: php artisan key:generate
    - name: Migrate database
      run: php artisan migrate
    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      run: php artisan test
    
